=== OctavioMaia/PLC_PRI/Aulas/Aula2/agenda.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT agenda (entrada | grupo)+ >
<!ELEMENT entrada (nome, email?, telefone) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT telefone (#PCDATA) >

<!ATTLIST  entrada
            id ID #REQUIRED
            tipo CDATA #REQUIRED >

<!ELEMENT grupo (entrada|grupo|referencia)+ >

<!ATTLIST grupo
            gid ID #REQUIRED>

<!ELEMENT referencia EMPTY >

<!ATTLIST referencia
            refent IDREF #REQUIRED >

=== OctavioMaia/PLC_PRI/Aulas/Aula2/DTD_Agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "file:/C:/Users/Octavio/Documents/GitHub/PLC_PRI/Aulas/Aula2/agenda.dtd">
<agenda>
    <entrada id="e1" tipo="pessoal">
        <nome>jcr</nome>
        <telefone>12345</telefone>
    </entrada>
    <entrada id="e2" tipo="pessoa">
        <nome>PRH</nome>
        <telefone>67890</telefone>
    </entrada>
    <entrada id="e3" tipo="pessoa">
        <nome>JJ</nome>
        <telefone>312312</telefone>
    </entrada>
    <grupo gid="gep1">
        <referencia refent="e2"/>
        <referencia refent="e3"/>
        <referencia refent="e1"/>
        <entrada id="e4" tipo="pessoa">
            <nome>Convidado1</nome>
            <telefone>142543534</telefone>
        </entrada>
    </grupo>
</agenda>
