=== OctavioMaia/PLC_PRI/Aulas/Aula2/livro-receitas.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT livro-de-receitas (abertura,receitas) >

<!ELEMENT abertura (autor,data,local) >
<!ELEMENT autor (#PCDATA) >
<!ELEMENT data  (#PCDATA) >
<!ELEMENT local (#PCDATA) >

<!ELEMENT receitas (receita+) >
<!ELEMENT receita (titulo, ingredientes, preparação) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT ingredientes (ingrediente+) >
<!ELEMENT ingrediente (#PCDATA) >

<!ATTLIST receita 
            língua CDATA #REQUIRED
            classificação CDATA #IMPLIED >

<!ELEMENT preparação (instrução+) >
<!ELEMENT instrução (#PCDATA)  >

=== OctavioMaia/PLC_PRI/Aulas/Aula2/DTD_Livro-receitas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE livro-de-receitas SYSTEM "file:/C:/Users/Octavio/Documents/GitHub/PLC_PRI/Aulas/Aula2/livro-receitas.dtd">
<livro-de-receitas>
    <abertura>
        <autor>José Carlos Ramalho</autor>
        <data>17 de Março de 2003</data>
        <local>Universidade do Minho</local>
    </abertura>
    <receitas>
        <receita língua="pt" classificação="doçaria">
            <titulo>Mousse de chocolate</titulo>
            <ingredientes>
                <ingrediente>200g de chocolate de chocolate de culinária</ingrediente>
                <ingrediente>50g de margarina</ingrediente>
                <ingrediente>meia dúzia de ovos</ingrediente>
                <ingrediente>4 colheres de sopa de açucar</ingrediente>
            </ingredientes>
            <preparação>
                <instrução>Separam-se as gemas das claras.</instrução>
                <instrução>Derrete-se o chocolate com a margarina.</instrução>
                <instrução>Adicionam-se as gemas.</instrução>
                <instrução>Mistura-se o açucar no chocolate.</instrução>
                <instrução>Batem-se as claras em castelo.</instrução>
                <instrução>Mistura-se tudo no recipiente final.</instrução>
            </preparação>
        </receita>
    </receitas>
</livro-de-receitas>
