=== OctavioMaia/PLC_PRI/Aulas/Aula2/poema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT poema (titulo, autor, corpo, data) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT autor (#PCDATA) >
<!ELEMENT data (#PCDATA) >

<!ELEMENT corpo (estrofe+) >
<!ELEMENT estrofe (verso+) >

<!ELEMENT verso (#PCDATA | nome | local)* >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT local (#PCDATA) >

=== OctavioMaia/PLC_PRI/Aulas/Aula2/DTD_teste.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE poema SYSTEM "file:/C:/Users/Octavio/Documents/GitHub/PLC_PRI/Aulas/Aula2/poema.dtd">
<poema>
    <titulo>Soneto JÃ¡ Antigo</titulo>
    <autor></autor>
    <corpo>
        <estrofe>
            <verso>dasdasd <nome>RUI</nome> d31239123</verso>
        </estrofe>
    </corpo>
    <data></data>
</poema>
