=== OctavioMaia/PLC_PRI/Aulas/Aula3/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pr (meta, team, abstract, deliverables) >
<!ELEMENT meta (id, title, subtitle?, bdate, edate, supervisor) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT bdate (#PCDATA) >
<!ELEMENT edate (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >

<!ATTLIST supervisor
            url CDATA #IMPLIED >

<!ELEMENT team (student+) >
<!ELEMENT student (name,nr,email) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT nr (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT abstract (p | img | code)+ >
<!ELEMENT p (#PCDATA | b | i | iref | xref )* >
<!ELEMENT b (#PCDATA | i | iref | xref )* >
<!ELEMENT i (#PCDATA | b | iref | xref )* >
<!ELEMENT iref (#PCDATA) >
<!ELEMENT xref (#PCDATA) >
<!ELEMENT img EMPTY >
<!ELEMENT code (#PCDATA) >

<!ATTLIST img
            src CDATA #REQUIRED>

<!ATTLIST xref
            url CDATA #REQUIRED >

<!ATTLIST iref
            url CDATA #REQUIRED >


<!ELEMENT deliverables (deliverable+) >
<!ELEMENT deliverable (#PCDATA)>

<!ATTLIST deliverable
            url CDATA #REQUIRED >

=== OctavioMaia/PLC_PRI/Aulas/Aula3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "file:/C:/Users/Octavio/Documents/GitHub/PLC_PRI/Aulas/Aula3/pr.dtd">
<pr>
    <meta>
        <id>PRI2017::A71369::TP2</id>
        <title>Project Record</title>
        <subtitle>Relatório gerado no trabalho prático nº2 da UC de PRI do MIEI 2017/2018.</subtitle>
        <bdate>25 de Setembro de 2017</bdate>
        <edate>26 de Setembro de 2017</edate>
        <supervisor url="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </meta>
    <team>
        <student>
            <name>Octávio José Azevedo Maia</name>
            <nr>A71369</nr>
            <email>a71369@alunos.uminho.pt</email>
        </student>
    </team>
    <abstract>
        <p>
            Neste trabalho prático nº2 foi proposta a criação de um <b>DTD</b> <i>(Document Type Definition)</i> e de um <b>XML</b> <i>(Extensible Markup Language)</i> acompanhante válido.
            De acordo com o <b>Project Record</b> fornecido, este foi também dividido em 4 partes: meta-informação, equipa de trabalho, resumo e anexos.
        </p>
        <p>
            Quase toda a especificação deste <b>DTD</b> é baseada na utilização do <i>#PCDATA</i>, exceto os vários links ou paths presentes neste project record.
            Foi escolhida esta forma de representação pois se assemelha mais ao estilo utilizado pelo <b>HTML</b>, sendo assim de mais fácil leitura.
        </p>
        <p>
            O resumo é composto de vários parágrafos, sendo que para suportar esta especificação foi criada uma lista de parágrafos à qual chamamos de <i>abstract</i>.
            Dentro dos parágrafos pode existir vários estilos de letra, como o negrito, itálico e sublinhado.
            Esta informção foi possível de representar através da criação de elementos apropriados, <b>b</b> para negrito, <b>i</b> para o itálico e <b>u</b> para o sublinhado.
        </p>
        <p>
            Por fim, foi criada uma lista de anexos, sendo que cada anexo consiste de um ficheiro, sendo que este está referenciado pelo seu <i>path</i>.
            Mais uma vez foi utilizada uma <b>ATTLIST</b>, sendo o atributo <b>path</b> de caráter obrigatório.
        </p>
    </abstract>
    <deliverables>
        <deliverable url="pr.dtd">Project Record (DTD)</deliverable>
        <deliverable url="pr.xml">Project Record (XML)</deliverable>
    </deliverables>
</pr>
