=== OctavioMaia/PLC_PRI/Aulas/Aula3/uc-aval.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT uc-aval (aval+) >

<!ELEMENT aval (aluno, tpcs, proj, teste) >

<!ELEMENT aluno (nome, numero, email) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT tpcs (tpc+)>
<!ELEMENT tpc (titulo, data, nota) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT data (#PCDATA) >
<!ELEMENT nota (#PCDATA) >

<!ELEMENT proj (titulo, data, nota) >

<!ELEMENT teste (data, nota) >

=== OctavioMaia/PLC_PRI/Aulas/Aula3/uc-aval.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE uc-aval SYSTEM "file:/C:/Users/Octavio/Documents/GitHub/PLC_PRI/Aulas/Aula3/uc-aval.dtd">
<uc-aval>
    <aval>
        <aluno>
            <nome>Joana Miguel</nome>
            <numero>A57127</numero>
            <email>A57127@alunos.uminho.pt</email>
        </aluno>
        <tpcs>
            <tpc>
                <titulo>Página HTML</titulo>
                <data>2017-09-25</data>
                <nota>1</nota>
            </tpc>
            <tpc>
                <titulo>DTD para o Project Record</titulo>
                <data>2017-10-2017</data>
                <nota>1</nota>
            </tpc>
        </tpcs>
        <proj>
            <titulo></titulo>
            <data></data>
            <nota></nota>
        </proj>
        <teste>
            <data></data>
            <nota></nota>
        </teste>
    </aval>
    <aval>
        <aluno>
            <nome>Bruno Ferreira</nome>
            <numero>A74155</numero>
            <email>A74155@alunos.uminho.pt</email>
        </aluno>
        <tpcs>
            <tpc>
                <titulo>Página HTML</titulo>
                <data>2017-09-25</data>
                <nota>1</nota>
            </tpc>
        </tpcs>
        <proj>
            <titulo></titulo>
            <data></data>
            <nota></nota>
        </proj>
        <teste>
            <data></data>
            <nota></nota>
        </teste>
    </aval>
</uc-aval>
